/* Generated By:JavaCC: Do not edit this line. ProjLangParserConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ProjLangParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int ADD = 5;
  /** RegularExpression Id. */
  int SUB = 6;
  /** RegularExpression Id. */
  int MUL = 7;
  /** RegularExpression Id. */
  int DIV = 8;
  /** RegularExpression Id. */
  int OR = 9;
  /** RegularExpression Id. */
  int AND = 10;
  /** RegularExpression Id. */
  int EQUALS = 11;
  /** RegularExpression Id. */
  int LESS_THAN = 12;
  /** RegularExpression Id. */
  int NOT = 13;
  /** RegularExpression Id. */
  int TRUE = 14;
  /** RegularExpression Id. */
  int FALSE = 15;
  /** RegularExpression Id. */
  int IF = 16;
  /** RegularExpression Id. */
  int THEN = 17;
  /** RegularExpression Id. */
  int ELSE = 18;
  /** RegularExpression Id. */
  int LET = 19;
  /** RegularExpression Id. */
  int VAL = 20;
  /** RegularExpression Id. */
  int IN = 21;
  /** RegularExpression Id. */
  int END = 22;
  /** RegularExpression Id. */
  int FUN = 23;
  /** RegularExpression Id. */
  int WHILE = 24;
  /** RegularExpression Id. */
  int DO = 25;
  /** RegularExpression Id. */
  int LPAR = 26;
  /** RegularExpression Id. */
  int RPAR = 27;
  /** RegularExpression Id. */
  int LCURL = 28;
  /** RegularExpression Id. */
  int RCURL = 29;
  /** RegularExpression Id. */
  int ASSIGN = 30;
  /** RegularExpression Id. */
  int SEMICOLON = 31;
  /** RegularExpression Id. */
  int ID = 32;
  /** RegularExpression Id. */
  int NUM = 33;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"|\"",
    "\"&\"",
    "\"=\"",
    "\"<\"",
    "\"!\"",
    "\"true\"",
    "\"false\"",
    "\"if\"",
    "\"then\"",
    "\"else\"",
    "\"let\"",
    "\"val\"",
    "\"in\"",
    "\"end\"",
    "\"fun\"",
    "\"while\"",
    "\"do\"",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\":=\"",
    "\";\"",
    "<ID>",
    "<NUM>",
  };

}
